/*  THIS FILE WAS GENERATED BY THE DATALIGHT RELIANCE EDGE CONFIGURATION
    UTILITY.  DO NOT MODIFY.

    Generated by configuration utility version 1.1
*/
/** @file
*/
#include <redconf.h>
#include <redtypes.h>
#include <redmacs.h>
#include <redvolume.h>


const VOLCONF gaRedVolConf[REDCONF_VOLUME_COUNT] =
{
    { 512U, 524288U, false, 10000U, 0U, "VOL0:"},
    { 1024U, 16384U, false, 10U, 0U, "VOL1:"},
    { 512U, 65536U, false, 100U, 0U, "VOL2:"},
    { 1024U, 16384U, false, 10U, 0U, "VOL3:"},
    { 512U, 65536U, false, 100U, 0U, "VOL4:"},
    { 2048U, 32768U, false, 10U, 0U, "VOL5:" }
};
