#
# Makefile for a Reliance Edge linux host tools project
#
P_BASEDIR ?= ../../..
P_PROJDIR ?= $(P_BASEDIR)/projects/linux/host
P_CONFDIR ?= $(P_PROJDIR)/..
B_DEBUG ?= 1

include $(P_BASEDIR)/os/linux/build/host.mk

