#
# Makefile for a Reliance Edge Win32 host tools project
#
P_BASEDIR ?= ../../../../..
P_PROJDIR ?= $(P_BASEDIR)/projects/freertos/atmel/sam4e-ek/host
P_CONFDIR ?= $(P_PROJDIR)/../src/config
B_DEBUG ?= 0

include $(P_BASEDIR)/os/win32/build/host.mk

